### ISSUE TITLE
UnpicklingError: invalid load key, 'v'.

### ISSUE THREAD

**Issue by rytakahas** [fhalab/embeddings_reproduction#11]
Hello,
many thanks for the github.

when I run test_predictions, i got following errors ...

UnpicklingError                           Traceback (most recent call last)
<ipython-input-7-47b1fab80736> in <module>
      1 with open('../inputs/X_aaindex_64_cosine.pkl', 'rb') as f:
----> 2     X_aa = pickle.load(f)

UnpicklingError: invalid load key, 'v'.
also, 
npicklingError                           Traceback (most recent call last)
<ipython-input-16-a654b33fe245> in <module>
     13 # Sequence and structure
     14 with open('../inputs/T50_seq_struct.pkl', 'rb') as f:
---> 15     X, _ = pickle.load(f)
     16 evals, mu = evaluate(df_train, df_test, X, y_col, 'seq_struc', guesses=(1, 100))
     17 res = pd.concat((res, evals), ignore_index=True)

UnpicklingError: invalid load key, 'v'.

my version 
print(np.__version__)
1.18.5
print(pd.__version__)
1.1.0.

or pkl files are corrupted?

thanks,

**Comment by yangkky** [comment]
Can you check that you have the correct pickled file? If you don't have git-lfs installed, it probably didn't pull the data properly from the repo when you cloned it.

**Comment by rytakahas** [comment]
Many thanks ...now it works fine! And, sorry to miss your note about GIT-LFS ... in readme.md.
