### ISSUE TITLE
Separate code from data

### ISSUE THREAD

**Issue by cthoyt** [fhalab/embeddings_reproduction#3]
I'm 7GB+ into trying to clone this repo and my computer is incredibly upset. I would suggest making a separate repository to house all of the data so the code can be downloaded and used independently.

**Comment by yangkky** [comment]
Right. The data is actually hosted separately already (link in the readme), so I should probably take it out of the repository.

**Comment by cthoyt** [comment]
Great! I think this also means that the links to the data sets in the Jupyter notebooks should also be updated (pandas handles URLs very smoothly 😄)

**Comment by yangkky** [comment]
Ok looking at this again, I need to move the inputs over to where the pre-trained embeddings are hosted. I'll do that later this week when I'm on campus and then update the notebooks to pull from the urls directly.

**Comment by cthoyt** [comment]
How big are the files with the pre-trained embeddings? Are those the ones that are multiple gigabytes? Because it might make sense to distribute this package with a pre-trained embeddings (or the underlying models that can be readily applied to a given sequence) in the package structure, and also give the user the ability to specify other ones from other places

**Comment by yangkky** [comment]
Yes, those are the ones that are really big. Is there a way to set up a package to install with large data files?

**Comment by cthoyt** [comment]
From how it looks to me, most of the big files are in the `input/` folder (~ 4.63 GB), and not the `output/` folder (~ 150 MB). I think I might have been mistaken before - isn't the `output/` the actual embeddings? If that's the case, then it's probably okay. 

What you would need to do is move the `output/` folder inside the `src/embeddings_reproduction/` folder, then the python scripts could find it with relative paths to themselves (I could also make a PR to demonstrate :smile:).

One thing to consider might be to switch from pickles to another format (I'm partial to JSON or JSON lines) that's gzipped. I bet that has better compression, too. Distributing pickles isn't really safe, since they can technically be used to trick Python into running arbitrary code.

**Comment by yangkky** [comment]
Do you mean move the `input` folder inside `src/embeddings_reproduction/`?

**Comment by cthoyt** [comment]
A power user should be free to download the input data and build new embeddings on their own, but an end user would just want the pre-trained embeddings. I think this corresponds to the `output` folder, right?
