### ISSUE TITLE
What is the path to the (final) protein embeddings?

### ISSUE THREAD

**Issue by phiweger** [fhalab/embeddings_reproduction#6]
Hi,

Somewhat related to #3 I cannot identify where to find the actual pretrained protein embedding. In `gensim` I would like to use `Word2Vec.load(path/to/embedding.model)` -- where can I find this?

Thank you

**Comment by yangkky** [comment]
The models are [here](http://cheme.caltech.edu/~kkyang/models/).

**Comment by phiweger** [comment]
Thanks!
