### ISSUE TITLE
Which model to use for computing new embeddings?

### ISSUE THREAD

**Issue by mengqvist** [fhalab/embeddings_reproduction#7]
As some users have noted before, in other issues, it is unclear how to use the final model to generate embeddings for a new set of protein sequences. I have identified the files located at http://cheme.caltech.edu/~kkyang/models/ and I have found the script embedding_tools.py from which I suppose the function get_embeddings_new() is the relevant one. But which doc2vec_file should I use to compute embeddings for my set of sequences? Which one is the "final" one?

As previously noted, if a minimal example of this was included in the main README file I am sure it would enable many more users to benefit from your work.

**Comment by yangkky** [comment]
I added a minimal example in the README. Let me know if you think anything else would be helpful. 

The choice of pretrained model should be treated as a hyperparameter. However, I find that no randomization (`original`) with `k=5` and `w >=2` to be a good starting point most of the time.

**Comment by mengqvist** [comment]
Thanks a lot! The minimal example is very helpful indeed!
